// ---------------------------------------------------------------------------
// execution.ts -- Type definitions for skill execution lifecycle
// ---------------------------------------------------------------------------

// ---- Status ----------------------------------------------------------------

/**
 * The discrete states a skill execution can be in.
 *
 * Lifecycle:  pending -> running -> completed | failed
 *             running -> cancelled  (user-initiated)
 */
export type ExecutionStatus =
  | 'pending'
  | 'running'
  | 'completed'
  | 'failed'
  | 'cancelled';

// ---- Output ----------------------------------------------------------------

/**
 * Metadata for a single file produced by a skill execution.
 * Files are written to the user's configured output directory.
 */
export interface OutputFile {
  /** Absolute path on disk where the file was written. */
  path: string;

  /** Human-readable file name (e.g. "Q4 Revenue Analysis.xlsx"). */
  name: string;

  /** File format / extension (without dot), e.g. "xlsx", "pdf", "pptx". */
  format: string;

  /** File size in bytes. Used for display ("1.2 MB") and quota tracking. */
  sizeBytes: number;
}

/**
 * The artifacts produced by a successful (or partially successful) execution.
 */
export interface ExecutionOutput {
  /**
   * The main output content.
   * Interpretation depends on the skill's manifest output type:
   *   - `table`    -> JSON-encoded row data
   *   - `markdown` -> rendered Markdown string
   *   - `file`     -> absolute path to the generated file
   */
  primary: string;

  /**
   * Optional secondary output content, following the same conventions
   * as `primary` but mapped to the manifest's `outputs.secondary` type.
   */
  secondary?: string;

  /**
   * List of all files generated during execution.
   * May include the primary output file as well as ancillary artifacts
   * (e.g. intermediate CSVs, log files).
   */
  outputFiles?: OutputFile[];
}

// ---- Error -----------------------------------------------------------------

/** Structured error returned when an execution fails. */
export interface ExecutionError {
  /**
   * Machine-readable error code for programmatic handling.
   * Examples: `"TIMEOUT"`, `"TOKEN_LIMIT_EXCEEDED"`, `"PARSE_ERROR"`,
   *           `"PERMISSION_DENIED"`, `"CLAUDE_CODE_ERROR"`.
   */
  code: string;

  /** Human-readable summary suitable for display in a toast / alert. */
  message: string;

  /**
   * Optional extended details (stack trace, Claude Code stderr, etc.).
   * Shown in the "Details" expander of the error panel.
   */
  details?: string;
}

// ---- Token Usage -----------------------------------------------------------

/**
 * Token consumption metrics for a single execution.
 * Populated by the Rust backend from the Claude Code CLI output.
 */
export interface TokenUsage {
  /** Number of tokens sent to the model (prompt + context). */
  inputTokens: number;

  /** Number of tokens generated by the model. */
  outputTokens: number;

  /**
   * Total tokens consumed (`inputTokens + outputTokens`).
   * Stored explicitly for convenience and fast aggregation.
   */
  totalTokens: number;

  /**
   * Estimated API cost in US dollars.
   * Calculated using the per-token rates at the time of execution.
   */
  estimatedCost: number;
}

// ---- Execution (aggregate) -------------------------------------------------

/**
 * Full representation of a single skill execution run.
 *
 * Created when the user clicks "Run", updated in real-time via Tauri events,
 * and persisted to the local SQLite database for the execution history view.
 */
export interface SkillExecution {
  /** Unique identifier for this execution (UUID v4). */
  id: string;

  /** Identifier of the skill that was executed (matches `InstalledSkill.id`). */
  skillId: string;

  /** Current lifecycle state. */
  status: ExecutionStatus;

  /**
   * Snapshot of the form values the user submitted.
   * Keys correspond to the field identifiers in `SkillInputSchema.properties`.
   * File fields contain absolute paths as strings.
   */
  inputs: Record<string, unknown>;

  /** ISO 8601 timestamp when the execution was created / enqueued. */
  startedAt: string;

  /**
   * ISO 8601 timestamp when the execution reached a terminal state
   * (`completed`, `failed`, or `cancelled`).
   */
  completedAt?: string;

  /** Artifacts produced on success. */
  output?: ExecutionOutput;

  /** Error information on failure. */
  error?: ExecutionError;

  /** Token consumption metrics (available once the execution finishes). */
  tokenUsage?: TokenUsage;

  /**
   * Wall-clock duration in milliseconds from `startedAt` to `completedAt`.
   * `undefined` while the execution is still in progress.
   */
  durationMs?: number;
}
